apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  labels:
    app.kubernetes.io/name: springboot-demo
    app.kubernetes.io/version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: springboot-demo
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: springboot-demo
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
      - name: springboot-demo
        image: lsdtrip/springboot-demo:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: lsd-pull-secret
