name: "Semantic Release"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  semantic-release:
    name: "Semantic Release"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
